// <auto-generated />
namespace SoftwareEngineeringP1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _10_16_16_AddingStatusAndPriceToFlights : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10_16_16_AddingStatusAndPriceToFlights));
        
        string IMigrationMetadata.Id
        {
            get { return "201610161851293_10_16_16_AddingStatusAndPriceToFlights"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
