// <auto-generated />
namespace SoftwareEngineeringP1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _10_11_16_CreatingUserRolesFlightsAirportTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10_11_16_CreatingUserRolesFlightsAirportTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201610112315316_10_11_16_CreatingUserRolesFlightsAirportTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
