// <auto-generated />
namespace SoftwareEngineeringP1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _10_12_16_RemovingUserAndRolesCreatingCorrectAspNetUserRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10_12_16_RemovingUserAndRolesCreatingCorrectAspNetUserRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201610130047342_10_12_16_RemovingUserAndRolesCreatingCorrectAspNetUserRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
